--- 
version: "2"
services: 
  db: 
    container_name: database
    environment: 
      - MYSQL_ROOT_PASSWORD=rootpassword
      - MYSQL_DATABASE=mydatabase
      - MYSQL_USER=mydbuser
      - MYSQL_PASSWORD=mydbpassword
    image: mariadb
    #The ports Secion allows the mysql client on the host to connect to the dbserver
    ports: 
      - "127.0.0.1:3306:3306"
    #uncomment the expose section and comment out the port section to allow only other containers to access mysql
#    expose: 
#      - "3306"
    restart: unless-stopped
    volumes: 
      - "$PWD/mysqldata:/var/lib/mysql"
      - "$PWD/configs/mysql:/etc/mysql"
  webserver: 
    build: build/webserver
    container_name: webserver
    environment: 
      - "APACHE_RUN_USER www-data"
      - "APACHE_RUN_GROUP www-data"
      - "APACHE_LOG_DIR /var/log/apache2"
      - "APACHE_LOCK_DIR /var/lock/apache2"
      - "APACHE_PID_FILE /var/run/apache2.pid"
    ports: 
      - "80:80"
    restart: unless-stopped
    volumes: 
      - "$PWD/webdata:/var/www"
      - "$PWD/configs/apache:/etc/apache2"
      - "$PWD/configs/php:/etc/php/7.0/apache2/"

